name: CRA with CI/CD
run-name: ${{ github.actor }} is testing out CI/CD 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --if-present
      - run: npm run build --if-present
      - run: npm test
  build_docker_image:
    runs-on: "ubuntu-20.04"
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GH_TOKEN }}